name: Release

on:
  push:
    tags:

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv python install
      - name: Set version
        run: sed -i "s/version =.*/version = $(echo -n \"${{ github.ref }}\" | sed "s/refs\/tags\///")/" pyproject.toml
      - run: uv build
      - run: uv publish
